### ISSUE TITLE
 test fail of 222: rpmkeys -Kv <unsigned> 2

### ISSUE THREAD

**Issue by syyhao1994** [rpm-software-management/rpm#1074]
Description of problem:
There is a test failure when building the rpm 4.15.1. The failure is also exist of fedora build log.
https://kojipkgs.fedoraproject.org//packages/rpm/4.15.1/2.fc32.1/data/logs/aarch64/build.log

Version-Release number of selected component (if applicable):
The version of rpm is 4.15.1.

How reproducible:
rpmbuild -ba rpm.spec

Steps to Reproduce:
1.rpmbuild -ba rpm.spec
2.
3.

Actual results:
Please send `tests/rpmtests.log' and all information you think might help:

   To: <rpm-maint@lists.rpm.org>
   Subject: [rpm 4.15.1] rpmtests: 222 failed

Expected results:
All test pass

**Comment by pmatilai** [comment]
Right, that should be fixed already in commit 7cb8ebdf92f7f3d42a12afb9720e142284e71810 (and the mess behind it)

**Comment by syyhao1994** [comment]
emm...It seems didn't solve the problem, I will try again.
By the way, I was wondering how to change the name of src.rpm by default.
I can change the name of rpm by revising the macros of %_rpmfilename, but i don't find the macros that can change the name of src.rpm.

**Comment by syyhao1994** [comment]
> Right, that should be fixed already in commit [7cb8ebd](https://github.com/rpm-software-management/rpm/commit/7cb8ebdf92f7f3d42a12afb9720e142284e71810) (and the mess behind it)

emm...It seems didn't solve the problem, I will try again.
By the way, I was wondering how to change the name of src.rpm by default.
I can change the name of rpm by revising the macros of %_rpmfilename, but i don't find the macros that can change the name of src.rpm.

**Comment by pmatilai** [comment]
Yeah I realized that commit already is in 4.15.1, so there's something else going on, but that's the mess its related to anyhow.

**Comment by syyhao1994** [comment]
> Yeah I realized that commit already is in 4.15.1, so there's something else going on, but that's the mess its related to anyhow.

Ok.
And how about my second question, do you have any suggetion?
Thank you.

By the way, I was wondering how to change the name of src.rpm by default.
I can change the name of rpm by revising the macros of %_rpmfilename, but i don't find the macros that can change the name of src.rpm.

**Comment by pmatilai** [comment]
Righty, finally got around to properly look at this: the test-suite expectations in the *release tarball* are wrong due to somehow missing commit db48f6b69bdea860a8fa687e95bcb370a86f9984 contents, despite this commit clearly being visible in the included ChangeLog file. Can't begin to guess as to what happened there.

**Comment by syyhao1994** [comment]
> Righty, finally got around to properly look at this: the test-suite expectations in the _release tarball_ are wrong due to somehow missing commit [db48f6b](https://github.com/rpm-software-management/rpm/commit/db48f6b69bdea860a8fa687e95bcb370a86f9984) contents, despite this commit clearly being visible in the included ChangeLog file. Can't begin to guess as to what happened there.

this commit seems already included in version of 4.15.1. The test still failed.

**Comment by syyhao1994** [comment]
I got my tar.bz here:
http://ftp.rpm.org/releases/rpm-4.15.x/rpm-4.15.1.tar.bz2

**Comment by pmatilai** [comment]
This has been fixed in newer releases, but it's looking unlikely that we'll do a 4.15.2, closing. Thanks for reporting though!
