### ISSUE TITLE
rpm --query --package` silently fails for non-existing files containing tilde

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#2069]
`rpm --query --package` does not work as documented.  If the specified file does not exist, the command should fail.  This is for some reason not the case if the file name contains `~`.

Steps to Reproduce:
```
$ koji download-build -q systemtap-4.6~pre16262021g84ef6bd9-3.fc35
$ rpm --query --package 'systemtap-4.6~pre16262021g84ef6bd9-3.fc35.src.rpm'
systemtap-4.6~pre16262021g84ef6bd9-3.fc35.armv7hl

$ rm -f systemtap-4.6~pre16262021g84ef6bd9-3.fc35.src.rpm
$ rpm --query --package 'systemtap-4.6~pre16262021g84ef6bd9-3.fc35.src.rpm'
$ echo $?
0

$ rpm --query --package 'systemtap-4.6.pre16262021g84ef6bd9-3.fc35.src.rpm' 
error: open of systemtap-4.6.pre16262021g84ef6bd9-3.fc35.src.rpm failed: No such file or directory
```

`./` prefix or escaping tilde with backslash does not help.

Originally reported at https://bugzilla.redhat.com/show_bug.cgi?id=2060439

**Comment by dmnks** [comment]
Indeed, this is related to `rpmGlob()` which I'm currently reworking, so let's see if this can be incorporated.

**Comment by yangchenguang94** [comment]
@pmatilai  
I found this bug has been fixed after debugging , Looks like rpmglob.c in this section
` if (!local || (!rpmIsGlob(av[j], 0) && strchr(path, '~') == NULL))`

The following commit fix it
https://github.com/rpm-software-management/rpm/commit/9e541c6a7da076bc1c1beb1ee45fd5fdd735358c

**Comment by dmnks** [comment]
Actually, not yet, 9e541c6 doesn't solve this, but #2159 does.

**Comment by dmnks** [comment]
To elaborate, the culprit is that a tilde is considered a "magic" char and thus is passed to `glob(3)` for expansion (as @yangchenguang94 correctly noted above) where it (and `rpmGlob()` by extension) doesn't produce any matches. Since we currently ignore such unmatched globs in `rpm --query --package`, they're just silently skipped.

This is being changed in #2159 where an unmatched glob is returned, making the code actually try to open it, just like it would a non-glob filename, which fails with a proper error message and return code.

The actual root cause here is the that the tilde has different semantics based on where it appears in a path, i.e. it's the home directory path or a version modifier, respectively, and we treat it as the former in `rpmGlob()`. This is not being changed in the above PR, however that doesn't matter much as the outcome will be the same.
