### ISSUE TITLE
rpm 4.20.0 alpha fallout #3 : urpmi's testsuite is broken by new rpm (%buildroot no more defined)

### ISSUE THREAD

**Issue by soig** [rpm-software-management/rpm#3144]
We are hitting issues on Mageia with 4.20.x.
The new alpha breaks urpmi's testsuite b/c of missing debuginfo:

> error: Empty %files file /home/tv/mga/git/mga/urpmi/t/tmp/BUILD/a-1-build/debugsourcefiles.list
> error: Empty %files file /home/tv/mga/git/mga/urpmi/t/tmp/BUILD/b-1-build/debugsourcefiles.list

But it's silly to try to extract debuginfo when there's no
I could make those pkgs noarch or set debug_package to %{nil}
On second though I wonder why this wasn't an issue before ?

I fixed those ones in urpmi.

But then I'm hitting this one:

> error: Bad exit status from /home/tv/mga/git/mga/urpmi/t/tmp/rpm-tmp.h09qUo (%install)
> 
> #   Failed test 'rpmbuild --quiet --define '_topdir /home/tv/mga/git/mga/urpmi/t/tmp' --define '_tmppath /home/tv/mga/git/mga/urpmi/t/tmp' -bb --clean --nodeps  --define '__os_install_post %nil' --define 'rpm_version %(rpm -q --queryformat "%{VERSION}" rpm|sed -e "s/\\.//g")'  data/SPECS/buildroot_default.spec'

This can be reproduced by running:
`rpmbuild   -bb --clean  t/data/SPECS/buildroot_default.spec`
(with https://gitweb.mageia.org/software/rpm/urpmi/tree/t/data/SPECS/buildroot_default.spec)
I've attached the rpmbuild output for both 4.19 & 4.20 which shows the regression
The issue is that the _buildrootdir macro disappeared in  commit 9d35c8df497534e1fbd806a4dc78802bcf35d7cb

Compare:

- rpm-4.19.1.1:
> $ rpm --eval %buildroot
> /home/tv/rpmbuild/BUILDROOT/%{NAME}-%{VERSION}-%{RELEASE}.x86_64

- rpm-4.19.91:
> $ rpm --eval %buildroot
> %buildroot

I can drop the test but I'm pretty sure the cople macros that were removed will explode quite a lot of spec files in the wild…

Note that we all those upstream patches have been backported:
0001-Ensure-noarch-packages-don-t-get-debuginfo.patch
0001-Fix-noprep-regression-from-introducing-mkbuilddir.patch
0002-Drop-an-accidentally-added-duplicated-test.patch
0003-Make-build-in-place-much-less-of-a-hack-and-also-wor.patch
0001-Fix-incomplete-header-on-plain-src.rpm-build-modes-r.patch
0001-Hammer-in-no-debuginfo-for-noarch-packages-damn-it-r.patch
0001-Fix-regression-on-subpackage-debuginfo-RPMTAG_SOURCE.patch
0001-Fix-a-buildroot-regression-on-an-early-__spec_instal.patch

[buildroot-rpm-4.20.txt](https://github.com/user-attachments/files/15545814/buildroot-rpm-4.20.txt)
[buildroot-rpm-4.19.txt](https://github.com/user-attachments/files/15545816/buildroot-rpm-4.19.txt)

**Comment by pmatilai** [comment]
%buildroot is still defined inside the build (starting with spec parse) which is the only place where it has a meaningful value. However I *really* didn't expect %{_buildrootdir} to be used in specs, but there it is, I see a handful in Fedora too. Packages shouldn't have any business messing with it, but as it happens with the new %builddir setup we can actually make that safe, so we just did: https://github.com/rpm-software-management/rpm/pull/3139

**Comment by pmatilai** [comment]
The sudden debuginfo extraction was intentional in that we wanted to make debuginfo available without requiring %setup as previously was the case, but turns out there are SO many unsuspecting things breaking because of it that it was just reverted: https://github.com/rpm-software-management/rpm/pull/3140

**Comment by pmatilai** [comment]
So these issues should be addressed in git master now, the PR's are cherry-pickable to 4.20.

**Comment by soig** [comment]
The macro is defined again but urpmi test still fails as the new value is different from the old one:
buildroot should be /home/tv/rpmbuild/BUILD/buildroot-1-build/buildroot-1-1.x86_64 instead of /home/tv/rpmbuild/BUILD/buildroot-1-build/BUILDROOT

Compare
- /home/tv/rpmbuild/BUILD/buildroot-1-build/buildroot-1-1.x86_64
- /home/tv/rpmbuild/BUILD/buildroot-1-build/BUILDROOT

**Comment by pmatilai** [comment]
urpmi shouldn't be looking at the buildroot name in the first place, really. For all practical purposes it's an rpm-internal implementation detail that unfortunately has been exposed in the past.

**Comment by pmatilai** [comment]
Looking at the buildroot_default.spec, it seems like a leftoever from the days when buildroot was optional. Rpm has enforced a buildroot on everything since >= 4.6.0, so over 15 years.
Instead of trying to patch it, consider whether that test actually serves some purpose now. It probably doesn't, and if there's a meaningful test buried within, separate it from the buildroot nonsense.

**Comment by soig** [comment]
Probably but still it uncovered the fact that those macros are still used in the wild :-)
urmi testsuite is quite good at catching rpm regressions :-)

**Comment by soig** [comment]
I guess I could check that it's defined (non empty string) and doesn't contain "%" instead…
